import { MigrationConfig, DryRunResult, MigrationSummary, TableMapping, ColumnMapping, ExportViewOptions } from './types';

// ─── SQL Generation ───────────────────────────────────────────────────────────

export function generateCreateSchemasSQL(config: MigrationConfig): string {
  const schemas = new Set<string>();
  for (const t of config.tables) {
    if (t.include && t.pgSchema !== 'public') schemas.add(t.pgSchema);
  }
  if (schemas.size === 0) return '';
  return Array.from(schemas)
    .map((s) => `CREATE SCHEMA IF NOT EXISTS "${s}";`)
    .join('\n');
}

function normalizeDefaultValue(col: ColumnMapping): string | null {
  const raw = col.defaultValue;
  if (raw === null || raw === undefined) return null;
  const value = String(raw).trim();
  if (!value) return "''";

  // Safe function/keyword defaults that PostgreSQL accepts directly.
  if (
    /^(CURRENT_TIMESTAMP(\(\d+\))?|NOW\(\)|CURRENT_DATE|CURRENT_TIME(\(\d+\))?|LOCALTIMESTAMP(\(\d+\))?|LOCALTIME(\(\d+\))?|gen_random_uuid\(\)|uuid_generate_v4\(\))$/i.test(
      value
    )
  ) {
    return value;
  }

  // Already quoted SQL literal.
  if (/^'.*'$/.test(value)) return value;

  // Numeric / boolean literals.
  if (/^-?\d+(\.\d+)?$/.test(value)) return value;
  if (/^(true|false)$/i.test(value)) return value.toUpperCase();

  // MySQL bit literal (e.g. b'0', b'1') -> numeric for PG compatibility.
  const bitMatch = value.match(/^b'([01])'$/i);
  if (bitMatch) return bitMatch[1];

  // NULL default is equivalent to no explicit default.
  if (/^null$/i.test(value)) return null;

  // Fallback: treat as plain string literal to avoid PG reading it as column reference.
  const escaped = value.replace(/'/g, "''");
  if (/JSON/i.test(col.pgType)) return `'${escaped}'::jsonb`;
  return `'${escaped}'`;
}

function columnDDL(col: ColumnMapping): string {
  let type = col.pgType;
  if (col.isPrimaryKey && col.indexStrategy === 'sequential') {
    // Use BY DEFAULT so migration can insert source key values when provided.
    if (type === 'INTEGER') type = 'INTEGER GENERATED BY DEFAULT AS IDENTITY';
    else if (type === 'BIGINT') type = 'BIGINT GENERATED BY DEFAULT AS IDENTITY';
  } else if (col.isPrimaryKey && col.indexStrategy === 'uuid') {
    type = 'UUID DEFAULT gen_random_uuid()';
  }

  const nullPart = col.nullable ? 'NULL' : 'NOT NULL';
  const pkPart = col.isPrimaryKey ? ' PRIMARY KEY' : '';
  const uniquePart = !col.isPrimaryKey && col.isUnique ? ' UNIQUE' : '';

  let defaultPart = '';
  const normalizedDefault = !col.isPrimaryKey ? normalizeDefaultValue(col) : null;
  if (normalizedDefault !== null) {
    defaultPart = ` DEFAULT ${normalizedDefault}`;
  }

  return `    "${col.pgName}" ${type} ${nullPart}${defaultPart}${pkPart}${uniquePart}`;
}

export function generateCreateTableSQL(table: TableMapping): string {
  const includedCols = table.columns.filter((c) => c.include);
  if (includedCols.length === 0) return '';

  const colLines = includedCols.map(columnDDL).join(',\n');
  return `CREATE TABLE IF NOT EXISTS "${table.pgSchema}"."${table.pgName}" (\n${colLines}\n);`;
}

export function generateCommentsSQL(table: TableMapping): string[] {
  const sqls: string[] = [];
  const schema = table.pgSchema;
  const tbl = table.pgName;

  if (table.description && table.description.trim()) {
    const escaped = table.description.trim().replace(/'/g, "''");
    sqls.push(`COMMENT ON TABLE "${schema}"."${tbl}" IS '${escaped}';`);
  }

  for (const col of table.columns.filter((c) => c.include)) {
    if (col.description && col.description.trim()) {
      const escaped = col.description.trim().replace(/'/g, "''");
      sqls.push(`COMMENT ON COLUMN "${schema}"."${tbl}"."${col.pgName}" IS '${escaped}';`);
    }
  }

  return sqls;
}

export function generateIndexesSQL(table: TableMapping): string[] {
  const sqls: string[] = [];
  for (const col of table.columns) {
    if (!col.include || col.isPrimaryKey || col.isUnique) continue;
    if (col.indexStrategy !== 'none') {
      sqls.push(
        `CREATE INDEX IF NOT EXISTS "idx_${table.pgName}_${col.pgName}" ON "${table.pgSchema}"."${table.pgName}" ("${col.pgName}");`
      );
    }
  }
  return sqls;
}

const DEFAULT_VIEW: ExportViewOptions = { includeSource: true, includeTarget: true };

export function generateMigrationSQL(config: MigrationConfig, view: ExportViewOptions = DEFAULT_VIEW): string {
  const includeSource = view.includeSource;
  const includeTarget = view.includeTarget;
  const lines: string[] = [
    `-- MySQL → PostgreSQL Migration Script`,
    `-- Generated: ${new Date().toISOString()}`,
    `-- Migration: ${config.name}`,
    `-- THIS IS A DRY RUN PREVIEW — Review before executing`,
    '',
    `-- 1. Create Schemas`,
    `-- =================`,
  ];

  const schemas = generateCreateSchemasSQL(config);
  if (schemas) lines.push(schemas);
  lines.push('');

  lines.push(`-- 2. Create Tables`, `-- =================`);
  for (const t of config.tables) {
    if (!t.include) continue;
    lines.push('');
    if (includeSource) lines.push(`-- Source: ${t.sourceDatabase}.${t.mysqlName}`);
    if (includeTarget) lines.push(`-- Target: ${t.pgSchema}.${t.pgName}`);
    const ddl = generateCreateTableSQL(t);
    if (ddl) lines.push(ddl);
  }

  lines.push('', `-- 3. Add Comments`, `-- =================`);
  for (const t of config.tables) {
    if (!t.include) continue;
    const commentSQLs = generateCommentsSQL(t);
    if (commentSQLs.length > 0) lines.push(...commentSQLs);
  }

  lines.push('', `-- 4. Create Indexes`, `-- =================`);
  for (const t of config.tables) {
    if (!t.include) continue;
    const idxSQLs = generateIndexesSQL(t);
    lines.push(...idxSQLs);
  }

  return lines.join('\n');
}

// ─── Validation ───────────────────────────────────────────────────────────────

export function validateMigrationConfig(config: MigrationConfig): DryRunResult {
  const errors: string[] = [];
  const warnings: string[] = [];
  const included = config.tables.filter((t) => t.include);

  if (included.length === 0) errors.push('No tables selected for migration');

  // Duplicate table names per schema
  const tableKeys = new Set<string>();
  for (const t of included) {
    const key = `${t.pgSchema}.${t.pgName}`;
    if (tableKeys.has(key)) errors.push(`Duplicate table name: "${t.pgSchema}"."${t.pgName}"`);
    else tableKeys.add(key);

    // Duplicate column names
    const colNames = new Set<string>();
    const includedCols = t.columns.filter((c) => c.include);
    for (const c of includedCols) {
      if (colNames.has(c.pgName)) errors.push(`Duplicate column "${c.pgName}" in table "${t.pgName}"`);
      else colNames.add(c.pgName);
    }

    // Primary key warning
    const hasPK = includedCols.some((c) => c.isPrimaryKey);
    if (!hasPK) warnings.push(`Table "${t.pgName}" has no primary key`);
  }

  const summary = buildSummary(config);
  const sqlScript = generateMigrationSQL(config);

  return { valid: errors.length === 0, errors, warnings, summary, sqlScript };
}

export function buildSummary(config: MigrationConfig): MigrationSummary {
  const included = config.tables.filter((t) => t.include);
  const schemas = new Set(included.map((t) => t.pgSchema));
  let totalColumns = 0;
  let totalIndexes = 0;
  for (const t of included) {
    const cols = t.columns.filter((c) => c.include);
    totalColumns += cols.length;
    totalIndexes += cols.filter((c) => !c.isPrimaryKey && c.indexStrategy !== 'none').length;
  }
  const estimatedStatements =
    (schemas.size > 1 ? schemas.size - 1 : 0) + included.length + totalIndexes;

  return {
    totalTables: config.tables.length,
    includedTables: included.length,
    totalColumns,
    totalIndexes,
    schemasToCreate: Array.from(schemas),
    estimatedStatements,
  };
}
