import type { NextApiRequest, NextApiResponse } from 'next';
import { verifyAccessToken } from '../../../lib/auth-store';
import { withPg, withMysql, type ExplorerConn } from '../../../lib/explorer-db';
import * as XLSX from 'xlsx';

type ExportFormat = 'sql' | 'xlsx';

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).end();

  const token = (req.headers.authorization ?? '').replace('Bearer ', '');
  if (!verifyAccessToken(token)) return res.status(401).json({ error: 'Unauthorized' });

  const { conn, tableKeys, format } = req.body as {
    conn: ExplorerConn;
    tableKeys: string[];
    format: ExportFormat;
  };

  if (!conn || !tableKeys?.length) {
    return res.status(400).json({ error: 'conn and tableKeys required' });
  }

  try {
    if (format === 'xlsx') {
      const wb = XLSX.utils.book_new();

      for (const key of tableKeys) {
        const parts = key.split('.');
        const [schema, table] = parts.length === 2 ? parts : ['public', parts[0]];

        let rows: any[] = [];
        if (conn.type === 'postgresql') {
          rows = await withPg(conn, async (client) => {
            const { rows: cols } = await client.query<any>(`
              SELECT
                c.column_name, c.data_type, c.udt_name,
                c.character_maximum_length, c.is_nullable, c.column_default,
                EXISTS(
                  SELECT 1 FROM information_schema.table_constraints tc
                  JOIN information_schema.key_column_usage kcu
                    ON kcu.constraint_name = tc.constraint_name
                  WHERE tc.constraint_type = 'PRIMARY KEY'
                    AND tc.table_schema = $1 AND tc.table_name = $2
                    AND kcu.column_name = c.column_name
                ) AS is_pk,
                pgd.description AS comment
              FROM information_schema.columns c
              LEFT JOIN pg_catalog.pg_statio_all_tables st
                ON st.schemaname = c.table_schema AND st.relname = c.table_name
              LEFT JOIN pg_catalog.pg_description pgd
                ON pgd.objoid = st.relid AND pgd.objsubid = c.ordinal_position
              WHERE c.table_schema = $1 AND c.table_name = $2
              ORDER BY c.ordinal_position
            `, [schema, table]);
            return cols;
          });
        } else {
          rows = await withMysql(conn, async (c) => {
            const [cols] = await c.query<any[]>(`
              SELECT COLUMN_NAME AS column_name, DATA_TYPE AS data_type,
                COLUMN_TYPE AS udt_name, CHARACTER_MAXIMUM_LENGTH AS character_maximum_length,
                IS_NULLABLE AS is_nullable, COLUMN_DEFAULT AS column_default,
                IF(COLUMN_KEY='PRI', TRUE, FALSE) AS is_pk,
                COLUMN_COMMENT AS comment
              FROM information_schema.COLUMNS
              WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
              ORDER BY ORDINAL_POSITION
            `, [schema, table]);
            return cols as any[];
          });
        }

        const sheetData = [
          ['Column', 'Type', 'Nullable', 'Default', 'PK', 'Comment'],
          ...rows.map(r => [
            r.column_name,
            r.character_maximum_length ? `${r.udt_name}(${r.character_maximum_length})` : r.udt_name,
            r.is_nullable === 'YES' ? 'YES' : 'NO',
            r.column_default ?? '',
            r.is_pk ? 'PK' : '',
            r.comment ?? '',
          ]),
        ];

        const sheetName = `${schema}.${table}`.slice(0, 31);
        XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(sheetData), sheetName);
      }

      // Summary sheet
      const summaryRows = [['Schema', 'Table', 'Included'], ...tableKeys.map(k => {
        const [s, t] = k.includes('.') ? k.split('.') : ['public', k];
        return [s, t, 'YES'];
      })];
      XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summaryRows), 'Summary');

      const buf = XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' });
      res.setHeader('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      res.setHeader('Content-Disposition', 'attachment; filename="data-model.xlsx"');
      return res.status(200).send(buf);
    }

    // SQL migration export
    const lines: string[] = [`-- Generated by Schema Explorer\n-- ${new Date().toISOString()}\n`];

    for (const key of tableKeys) {
      const parts = key.split('.');
      const [schema, table] = parts.length === 2 ? parts : ['public', parts[0]];

      if (conn.type === 'postgresql') {
        await withPg(conn, async (client) => {
          const { rows: cols } = await client.query<any>(`
            SELECT c.column_name, c.udt_name, c.character_maximum_length,
              c.numeric_precision, c.numeric_scale, c.is_nullable, c.column_default
            FROM information_schema.columns c
            WHERE c.table_schema = $1 AND c.table_name = $2
            ORDER BY c.ordinal_position
          `, [schema, table]);

          const { rows: pkRows } = await client.query<{ col: string }>(`
            SELECT kcu.column_name AS col
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema
            WHERE tc.constraint_type = 'PRIMARY KEY'
              AND tc.table_schema = $1 AND tc.table_name = $2
            ORDER BY kcu.ordinal_position
          `, [schema, table]);
          const pks = new Set(pkRows.map(r => r.col));

          const { rows: fkRows } = await client.query<any>(`
            SELECT kcu.column_name AS from_col,
              ccu.table_schema AS ref_schema, ccu.table_name AS ref_table, ccu.column_name AS ref_col,
              tc.constraint_name
            FROM information_schema.table_constraints tc
            JOIN information_schema.key_column_usage kcu
              ON kcu.constraint_name = tc.constraint_name AND kcu.table_schema = tc.table_schema
            JOIN information_schema.referential_constraints rc
              ON rc.constraint_name = tc.constraint_name AND rc.constraint_schema = tc.table_schema
            JOIN information_schema.key_column_usage ccu
              ON ccu.constraint_name = rc.unique_constraint_name AND ccu.table_schema = rc.unique_constraint_schema
            WHERE tc.constraint_type = 'FOREIGN KEY'
              AND tc.table_schema = $1 AND tc.table_name = $2
          `, [schema, table]);

          const colDefs = cols.map(c => {
            let typeDef = c.udt_name;
            if (c.character_maximum_length) typeDef += `(${c.character_maximum_length})`;
            else if (c.numeric_precision && ['numeric', 'decimal'].includes(c.udt_name))
              typeDef += `(${c.numeric_precision},${c.numeric_scale ?? 0})`;
            const notNull = c.is_nullable === 'NO' ? ' NOT NULL' : '';
            const def = c.column_default ? ` DEFAULT ${c.column_default}` : '';
            return `  ${c.column_name} ${typeDef}${notNull}${def}`;
          });

          if (pks.size)
            colDefs.push(`  PRIMARY KEY (${[...pks].join(', ')})`);

          fkRows.forEach(fk => {
            colDefs.push(
              `  CONSTRAINT ${fk.constraint_name} FOREIGN KEY (${fk.from_col}) REFERENCES ${fk.ref_schema}.${fk.ref_table}(${fk.ref_col})`
            );
          });

          lines.push(`CREATE TABLE IF NOT EXISTS ${schema}.${table} (\n${colDefs.join(',\n')}\n);\n`);
        });
      } else {
        await withMysql(conn, async (c) => {
          const [cols] = await c.query<any[]>(`
            SELECT COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY, EXTRA
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = ? AND TABLE_NAME = ?
            ORDER BY ORDINAL_POSITION
          `, [schema, table]);

          const [fkRows] = await c.query<any[]>(`
            SELECT kcu.COLUMN_NAME AS from_col,
              kcu.REFERENCED_TABLE_SCHEMA AS ref_schema,
              kcu.REFERENCED_TABLE_NAME AS ref_table,
              kcu.REFERENCED_COLUMN_NAME AS ref_col,
              kcu.CONSTRAINT_NAME
            FROM information_schema.KEY_COLUMN_USAGE kcu
            JOIN information_schema.TABLE_CONSTRAINTS tc
              ON tc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME AND tc.TABLE_SCHEMA = kcu.TABLE_SCHEMA
            WHERE tc.CONSTRAINT_TYPE = 'FOREIGN KEY'
              AND kcu.TABLE_SCHEMA = ? AND kcu.TABLE_NAME = ?
          `, [schema, table]);

          const colDefs = (cols as any[]).map(c => {
            const notNull = c.IS_NULLABLE === 'NO' ? ' NOT NULL' : '';
            const def = c.COLUMN_DEFAULT !== null ? ` DEFAULT ${c.COLUMN_DEFAULT}` : '';
            const pk = c.COLUMN_KEY === 'PRI' ? ' PRIMARY KEY' : '';
            const extra = c.EXTRA ? ` ${c.EXTRA}` : '';
            return `  \`${c.COLUMN_NAME}\` ${c.COLUMN_TYPE}${notNull}${def}${extra}${pk}`;
          });

          (fkRows as any[]).forEach(fk => {
            colDefs.push(
              `  CONSTRAINT \`${fk.CONSTRAINT_NAME}\` FOREIGN KEY (\`${fk.from_col}\`) REFERENCES \`${fk.ref_schema}\`.\`${fk.ref_table}\`(\`${fk.ref_col}\`)`
            );
          });

          lines.push(`CREATE TABLE IF NOT EXISTS \`${schema}\`.\`${table}\` (\n${colDefs.join(',\n')}\n);\n`);
        });
      }
    }

    res.setHeader('Content-Type', 'text/plain');
    res.setHeader('Content-Disposition', 'attachment; filename="migration.sql"');
    return res.status(200).send(lines.join('\n'));
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return res.status(500).json({ error: msg });
  }
}
