import { MigrationConfig, MigrationSummary } from './types';
import { buildSummary, generateMigrationSQL } from './postgres-migrator';

export function generateMarkdownDocumentation(config: MigrationConfig): string {
  const summary = buildSummary(config);
  const date = new Date().toISOString().split('T')[0];
  const included = config.tables.filter((t) => t.include);

  const lines: string[] = [
    `# MySQL → PostgreSQL Migration Document`,
    ``,
    `**Generated:** ${date}`,
    `**Migration Name:** ${config.name}`,
    `**Status:** ${config.status}`,
    `**Source Database:** ${config.sourceDatabase}`,
    `**Target Database:** ${config.targetDatabase}`,
    ``,
    `## Executive Summary`,
    ``,
    `This document details the migration of **${summary.includedTables}** tables from MySQL \`${config.sourceDatabase}\` to PostgreSQL.`,
    ``,
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Tables to migrate | ${summary.includedTables} |`,
    `| Total columns | ${summary.totalColumns} |`,
    `| Indexes to create | ${summary.totalIndexes} |`,
    `| PostgreSQL schemas | ${summary.schemasToCreate.join(', ')} |`,
    ``,
    `## Table Mapping Summary`,
    ``,
    `| MySQL Table | PostgreSQL Schema | PostgreSQL Table | Include |`,
    `|-------------|-------------------|------------------|---------|`,
    ...config.tables.map(
      (t) =>
        `| \`${t.mysqlName}\` | \`${t.pgSchema}\` | \`${t.pgName}\` | ${t.include ? '✓' : '✗'} |`
    ),
    ``,
    `## Detailed Table Mappings`,
  ];

  for (const t of included) {
    lines.push(
      ``,
      `### ${t.pgSchema}.${t.pgName}`,
      ``,
      t.description ? `**Purpose:** ${t.description}` : '',
      ``,
      `| MySQL Column | MySQL Type | PostgreSQL Column | PG Type | PK | Nullable |`,
      `|-------------|-----------|------------------|---------|-----|----------|`,
      ...t.columns
        .filter((c) => c.include)
        .map(
          (c) =>
            `| \`${c.mysqlName}\` | ${c.mysqlType} | \`${c.pgName}\` | ${c.pgType} | ${c.isPrimaryKey ? 'YES' : ''} | ${c.nullable ? 'YES' : 'NO'} |`
        )
    );
  }

  lines.push(
    ``,
    `## Pre-Migration Checklist`,
    ``,
    `- [ ] Backup MySQL database`,
    `- [ ] Backup PostgreSQL database (if existing)`,
    `- [ ] Test migration on staging environment`,
    `- [ ] Verify all data type conversions`,
    `- [ ] Check foreign key relationships`,
    `- [ ] Validate row counts post-migration`,
    `- [ ] Test application with new schema`,
    `- [ ] Plan downtime window`,
    ``,
    `## Rollback Plan`,
    ``,
    `1. Keep MySQL database untouched during migration`,
    `2. Store PostgreSQL connection details separately`,
    `3. If migration fails, revert application to MySQL`,
    `4. Drop partially-created PostgreSQL schemas if needed`,
    ``,
    `---`,
    `*Generated by MySQL→PostgreSQL Migration Tool*`
  );

  return lines.filter((l) => l !== undefined).join('\n');
}

export function generateSQLDocumentation(config: MigrationConfig): string {
  return generateMigrationSQL(config);
}
