import type { NextApiRequest, NextApiResponse } from 'next';
import { verifyAccessToken } from '../../../lib/auth-store';
import { sanitizeName } from '../../../lib/normalizer/profiler';

interface ConfirmedLookup {
  colName: string;
  colIndex: number;
  lookupTable: string;
  distinctValues: string[];
}

interface ExportSheet {
  tableName: string;
  headers: string[];
  allRows: string[][];
}

interface ExportBody {
  mode: 'sql' | 'csv' | 'json';
  sheet: ExportSheet;
  confirmedLookups: ConfirmedLookup[];
}

function escapeSql(v: string, type: string): string {
  if (v === '' || v === null || v === undefined) return 'NULL';
  if (['INTEGER', 'BIGINT', 'NUMERIC'].includes(type)) return v.trim();
  if (type === 'BOOLEAN') return ['true', 'yes', '1'].includes(v.toLowerCase()) ? 'TRUE' : 'FALSE';
  return `'${v.replace(/'/g, "''")}'`;
}

function inferColType(vals: string[]): string {
  const ne = vals.filter(v => v.trim() !== '');
  if (!ne.length) return 'TEXT';
  if (ne.every(v => /^-?\d+$/.test(v.trim()))) return ne.some(v => Math.abs(Number(v)) > 2147483647) ? 'BIGINT' : 'INTEGER';
  if (ne.every(v => /^-?\d+(\.\d+)?$/.test(v.trim()))) return 'NUMERIC';
  const boolSet = new Set(['true', 'false', 'yes', 'no', '1', '0']);
  if (ne.every(v => boolSet.has(v.toLowerCase()))) return 'BOOLEAN';
  if (ne.every(v => /^\d{4}-\d{2}-\d{2}[T ]\d{2}:\d{2}/.test(v))) return 'TIMESTAMP';
  if (ne.every(v => /^\d{4}-\d{2}-\d{2}$/.test(v))) return 'DATE';
  return 'TEXT';
}

function generateSql(sheet: ExportSheet, lookups: ConfirmedLookup[]): string {
  const lines: string[] = [`-- Generated by Data Normalizer\n-- ${new Date().toISOString()}\n`];
  const lookupMap = new Map(lookups.map(l => [l.colIndex, l]));

  // Lookup tables
  for (const lk of lookups) {
    lines.push(`CREATE TABLE IF NOT EXISTS ${lk.lookupTable} (\n  id SERIAL PRIMARY KEY,\n  value TEXT NOT NULL UNIQUE\n);\n`);
    const vals = lk.distinctValues.map(v => `  ('${v.replace(/'/g, "''")}')`).join(',\n');
    lines.push(`INSERT INTO ${lk.lookupTable} (value) VALUES\n${vals}\nON CONFLICT (value) DO NOTHING;\n`);
  }

  // Main table schema
  const colDefs: string[] = [];
  const colTypes: string[] = [];
  for (let i = 0; i < sheet.headers.length; i++) {
    const colName = sanitizeName(sheet.headers[i]);
    const lk = lookupMap.get(i);
    if (lk) {
      colDefs.push(`  ${colName}_id INTEGER REFERENCES ${lk.lookupTable}(id)`);
      colTypes.push('FK');
    } else {
      const vals = sheet.allRows.map(r => r[i] ?? '');
      const t = inferColType(vals);
      colTypes.push(t);
      colDefs.push(`  ${colName} ${t}`);
    }
  }
  lines.push(`CREATE TABLE IF NOT EXISTS ${sheet.tableName} (\n  id SERIAL PRIMARY KEY,\n${colDefs.join(',\n')}\n);\n`);

  // Main table inserts
  const insertCols: string[] = [];
  for (let i = 0; i < sheet.headers.length; i++) {
    const colName = sanitizeName(sheet.headers[i]);
    insertCols.push(lookupMap.has(i) ? `${colName}_id` : colName);
  }

  const valueRows = sheet.allRows.map(row => {
    const vals = row.map((v, i) => {
      const lk = lookupMap.get(i);
      if (lk) {
        return `(SELECT id FROM ${lk.lookupTable} WHERE value = '${v.replace(/'/g, "''")}')`;
      }
      return escapeSql(v, colTypes[i] ?? 'TEXT');
    });
    return `  (${vals.join(', ')})`;
  });

  if (valueRows.length) {
    lines.push(`INSERT INTO ${sheet.tableName} (${insertCols.join(', ')}) VALUES\n${valueRows.join(',\n')};\n`);
  }

  return lines.join('\n');
}

function generateCsv(sheet: ExportSheet, lookups: ConfirmedLookup[]): string {
  const lookupMap = new Map(lookups.map(l => [l.colIndex, l]));
  const headers = sheet.headers.map((h, i) => {
    const lk = lookupMap.get(i);
    return lk ? `${sanitizeName(h)}_id` : sanitizeName(h);
  });

  const valueIdxMap = new Map(lookups.map(lk => [lk.colIndex, new Map(lk.distinctValues.map((v, i) => [v, i + 1]))]));

  const escape = (v: string) => v.includes(',') || v.includes('"') || v.includes('\n') ? `"${v.replace(/"/g, '""')}"` : v;

  const dataLines = sheet.allRows.map(row => {
    return row.map((v, i) => {
      const idxMap = valueIdxMap.get(i);
      return escape(idxMap ? String(idxMap.get(v) ?? '') : v);
    }).join(',');
  });

  return [headers.join(','), ...dataLines].join('\n');
}

function generateJson(sheet: ExportSheet, lookups: ConfirmedLookup[]): string {
  const lookupMap = new Map(lookups.map(l => [l.colIndex, l]));
  const valueIdxMap = new Map(lookups.map(lk => [lk.colIndex, new Map(lk.distinctValues.map((v, i) => [v, i + 1]))]));

  const result: Record<string, unknown> = {};

  // Lookup tables as arrays
  for (const lk of lookups) {
    result[lk.lookupTable] = lk.distinctValues.map((v, i) => ({ id: i + 1, value: v }));
  }

  // Main table
  result[sheet.tableName] = sheet.allRows.map((row, ri) => {
    const obj: Record<string, unknown> = { id: ri + 1 };
    row.forEach((v, i) => {
      const colName = sanitizeName(sheet.headers[i]);
      const lk = lookupMap.get(i);
      const idxMap = valueIdxMap.get(i);
      if (lk && idxMap) {
        obj[`${colName}_id`] = idxMap.get(v) ?? null;
      } else {
        obj[colName] = v === '' ? null : v;
      }
    });
    return obj;
  });

  return JSON.stringify(result, null, 2);
}

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).end();

  const token = (req.headers.authorization ?? '').replace('Bearer ', '');
  if (!verifyAccessToken(token)) return res.status(401).json({ error: 'Unauthorized' });

  const { mode, sheet, confirmedLookups } = req.body as ExportBody;
  if (!mode || !sheet) return res.status(400).json({ error: 'mode and sheet required' });

  try {
    let content: string;
    let filename: string;
    let mimeType: string;

    if (mode === 'sql') {
      content = generateSql(sheet, confirmedLookups ?? []);
      filename = `${sheet.tableName}_normalized.sql`;
      mimeType = 'text/plain';
    } else if (mode === 'csv') {
      content = generateCsv(sheet, confirmedLookups ?? []);
      filename = `${sheet.tableName}_normalized.csv`;
      mimeType = 'text/csv';
    } else {
      content = generateJson(sheet, confirmedLookups ?? []);
      filename = `${sheet.tableName}_normalized.json`;
      mimeType = 'application/json';
    }

    res.setHeader('Content-Type', mimeType);
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);
    return res.status(200).send(content);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return res.status(500).json({ error: msg });
  }
}
